### ISSUE TITLE
Importing Data from a Single File ('-a) No Longer Functions

### ISSUE THREAD

**Issue by jclayton40** [rockcarver/frodo-cli#125]
## Frodo CLI version
Provide output of `frodo -v`

You seem to be running the NPM package
Installed versions:
cli: v0.18.2-4
lib: v0.16.2-5
node: v16.15.1

## Describe the issue
When trying to import allThemes.json, allTemplates.json, etc fails.  Here is the command being executed:

frodo email template import -a allTemplates.json $target2 $realm $user $pass

##Error

TypeError: Cannot read properties of undefined (reading 'brightRed')
    at error (/usr/local/lib/node_modules/@rockcarver/frodo-cli/esm/utils/utils/Console.ts:84:26)
    at null.printMessage (/usr/local/lib/node_modules/@rockcarver/frodo-cli/esm/utils/utils/Console.ts:166:7)
    at printMessage (file:///usr/local/lib/node_modules/@rockcarver/frodo-cli/node_modules/@rockcarver/frodo-lib/esm/ops/utils/Console.mjs:20:5)
    at authenticate (file:///usr/local/lib/node_modules/@rockcarver/frodo-cli/node_modules/@rockcarver/frodo-lib/esm/ops/AuthenticateOps.mjs:219:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getTokens (file:///usr/local/lib/node_modules/@rockcarver/frodo-cli/node_modules/@rockcarver/frodo-lib/esm/ops/AuthenticateOps.mjs:342:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/@rockcarver/frodo-cli/esm/cli/email/cli/email/email-template-import.ts:54:11)

However, if  export all templates or themes as individual files, you can use -A to import the entire directory. The problem is, the customer/end-user doesn't want 200 separate .json floating around on their system.

**Comment by vscheuber** [comment]
You need to provide `-f` to indicate the file to import:
```
% frodo theme import -a -f allAlphaThemes.theme.json frodo bravo
ForgeRock Identity Cloud detected.
Connected to [https://openam-frodo-dev.forgeblocks.com/am], [bravo] realm, as [volker.scheuber@forgerock.com]
Importing all themes from a single file (allAlphaThemes.theme.json)...
[========================================] 100% | 33/33 | Successfully imported 33 themes.
%
```
